### ISSUE TITLE
program_name not taken into account under Xubuntu 18.04

### ISSUE THREAD

**Issue by NathanRichard** [chriskiehl/Gooey#346] opened 2018-11-05 08:44 UTC
- OS version : Ubuntu 18.04.1 LTS x86_64 (Xubuntu flavor)
 - Python Version : Python 3.7.0 
 - Gooey Version: 1.0.2
 - Thorough description of problem :
     -  Expected Behavior : string provided in program_name should appear in window title bar.
     - Actual Behavior: Titlebar shows only the gooey icon. System windows list show "Fenêtre sans titre" due to french localisation which translates to "Title-less Window". 
 - A minimal code example : please refer to https://gist.github.com/NathanRichard/179756853a0920c386cb5474dd4c5f64
 - Screenshot (if visual quirk) 
![image](https://user-images.githubusercontent.com/1778774/47987022-b3e08f00-e0de-11e8-928d-04d79603c2f3.png)
![image](https://user-images.githubusercontent.com/1778774/47987102-f609d080-e0de-11e8-8487-3d98bac4f6f6.png)
 - Anything else you may think will be helpful:
    - Desktop Environment : Xfce
    - Window manager : Xfwm4
    - Window manager theme: Numix

Thanks in advance for your help,
Nathan Richard

**Comment by chriskiehl** [comment] 2018-11-05 17:09
Duplicate of https://github.com/chriskiehl/Gooey/issues/303. Resolved in upcoming release.

**Closed by chriskiehl** 2018-11-05 17:09 UTC
