### ISSUE TITLE
Error in Phoenix

### ISSUE THREAD

**Issue by dev72** [chriskiehl/Gooey#198] opened 2017-05-11 10:20 UTC
File "C:\Python27\lib\site-packages\gooey\__init__.py", line 2, in <module>
    from gooey.python_bindings.gooey_decorator import Gooey
  File "C:\Python27\lib\site-packages\gooey\python_bindings\gooey_decorator.py", line 14, in <module>
    from gooey.gui import application
  File "C:\Python27\lib\site-packages\gooey\gui\application.py", line 8, in <module>
    from gooey.gui.controller import Controller
  File "C:\Python27\lib\site-packages\gooey\gui\controller.py", line 3, in <module>
    from gooey.gui.windows.base_window import BaseWindow
  File "C:\Python27\lib\site-packages\gooey\gui\windows\base_window.py", line 14, in <module>
    from gooey.gui.windows import footer, header, layouts
  File "C:\Python27\lib\site-packages\gooey\gui\windows\footer.py", line 8, in <module>
    import wx.animate
ImportError: No module named animate

**Comment by bilderbuchi** [comment] 2017-05-11 12:29
See if you can use #197, specifically [this](https://github.com/chriskiehl/Gooey/pull/197/files#diff-e0c2047f6e92ef0dc45c6c33c45ee202L8), I guess.

**Comment by rickdonnelly** [comment] 2017-06-09 21:29
I've encountered the same error, but see nothing in #197 that gets around this. I'm keen to see you move from wxPython to PyQt5, but would guess that is off in the distant future? In the meantime should I just assume that wxPython 4.x and Gooey are incompatible?

**Comment by Fredr1kh** [comment] 2017-07-01 00:50
Isn't the solution from #143 correct here?

"Go to Python27/Lib/site-packages and find the 'wx--msw' folder there.
Open the 'wx--msw' folder and move the 'wx' folder out into Python27/Lib/site-packages"

**Comment by chriskiehl** [comment] 2017-10-15 23:19
Dupe of #143

**Closed by chriskiehl** 2017-10-15 23:19 UTC
