### ISSUE TITLE
Get "This program needs access to the screen" using (PyInstaller) on MacOS Mojave

### ISSUE THREAD

**Issue by engdan77** [chriskiehl/Gooey#348] opened 2018-11-09 11:07 UTC
Hello There, Future Issue Creator! 

If you've found a bug, make sure to include the following:

[X] OS
MacOS 10.14 (Mojave)

[X] Python Version 
Python 3.7.1 (installed from python.org) and also Mac built-in Python 2.7.15

[X ] Gooey Version 
Latest commit revision abd69a9bae66c4f81e294742b32d53a76537c400

[X ] Thorough description of problem 
The problem is that I've tried all combinations to get a runnable "freezed" packages by using PyInstaller and cx_freeze. Also tried different combinations of Python (installed through pyenv, brew and finally MacPython from Python.org). But I will only focusing on explaining the Python 3.7.1 and Python 2.7.15 on Mojave scenarios. 

With both setups I've used the included widget_demo.py in the source that works running using 
- /Library/Frameworks/Python.framework/Versions/3.7/bin/python3 (from python.org)
- /usr/local/bin/python2 (built-in)

when calling it directly from python2/python3 (on command-line)

But as soon as you package using latest PyInstaller 3.5.dev0+b1be6a73e. (but also 3.4) using the below spec-file (but also tried many other combinations), it'll always successfully creates the packages but when you run this either trough terminal you get

_"This program needs access to the screen. Please run with a
Framework build of python, and only when you are logged in
on the main display of your Mac."_  
(you get the whole debug below)

Because I have packaged a very simple wx Python-script successfully using same PyInstaller without this message (considering MacOS nor PyInstaller being the problem), and tried all combinations of Pythons (brew, macPython, built-in) I have the believe that there is something related to Gooey in combination with PyInstaller (and using the sample provided considering not the code being the problem)

[X] Expected Behavior 
You should get the widget_demo window appearing

[X] Actual Behavior 
You get this "This program needs access to the screen. " you run the compiled "single file" binary
- dist/widget_demo

or you find that nothings happens if you open
- dist/widget_demo.app (through finder)

[X] A minimal code example 
I've used widget_demo.py from 
https://github.com/chriskiehl/GooeyExamples/blob/master/examples/widget_demo.py

widget_demo.spec (attached) <-- for PyInstaller
I've tested the variation of
``` 
hiddenimports=['wx', 'gooey'] and hiddenimports=[]
```

```
excludes=['FixTk', 'tcl', 'tk', '_tkinter', 'tkinter', 'Tkinter'] and excludes=[] <-- due to error in PyInstaller
```

I've compiled the package using

```
python3 -m PyInstaller -F --windowed widget_demo.spec
```
and
```
python2 -m PyInstaller -F --windowed widget_demo.spec
```

(but also tried all combinations of not using -F or --windowed)

[X] Screenshot (if visual quirk)
N/A - problem is that not GUI shown
 
[X] Anything else you may think will be helpful 
 The complete debug when running 

**Package by PyInstaller**

```
Daniels-MacBook-Air:gooey_test development$ python3 -m PyInstaller -F --windowed widget_demo.spec
334 INFO: PyInstaller: 3.5.dev0+b1be6a73e
334 INFO: Python: 3.7.1
343 INFO: Platform: Darwin-18.0.0-x86_64-i386-64bit
349 INFO: UPX is not available.
1189 INFO: checking Tree
1189 INFO: Building Tree because Tree-00.toc is non existent
1189 INFO: Building Tree Tree-00.toc
1194 INFO: checking Tree
1194 INFO: Building Tree because Tree-01.toc is non existent
1194 INFO: Building Tree Tree-01.toc
1197 INFO: Extending PYTHONPATH with paths
['/Users/development/git/my/gooey_test', '/Users/development/git/my/gooey_test']
1197 INFO: checking Analysis
1198 INFO: Building Analysis because Analysis-00.toc is non existent
1198 INFO: Initializing module dependency graph...
1203 INFO: Initializing module graph hooks...
1211 INFO: Analyzing base_library.zip ...
5491 INFO: Analyzing hidden import 'wx'
5662 INFO: Analyzing hidden import 'gooey'
5849 INFO: Processing pre-safe import module hook   six.moves
8820 INFO: running Analysis Analysis-00.toc
8848 INFO: Caching module hooks...
8852 INFO: Analyzing widget_demo.py
8867 INFO: Loading module hooks...
8868 INFO: Loading module hook "hook-xml.etree.cElementTree.py"...
8871 INFO: Loading module hook "hook-encodings.py"...
8938 INFO: Loading module hook "hook-PIL.py"...
8943 INFO: Excluding import 'PyQt4'
8944 INFO:   Removing import of PyQt4 from module PIL.ImageQt
8944 INFO: Excluding import 'tkinter'
8945 INFO: Excluding import 'PyQt5'
8946 INFO:   Removing import of PyQt5 from module PIL.ImageQt
8946 INFO: Excluding import 'FixTk'
8947 INFO: Excluding import 'PySide'
8948 INFO:   Removing import of PySide from module PIL.ImageQt
8949 INFO: Loading module hook "hook-PIL.Image.py"...
9033 INFO: Processing pre-find module path hook   distutils
9514 INFO: Loading module hook "hook-gooey.py"...
9526 INFO: Loading module hook "hook-xml.py"...
9807 INFO: Loading module hook "hook-pydoc.py"...
9810 INFO: Loading module hook "hook-distutils.py"...
9815 INFO: Loading module hook "hook-PIL.SpiderImagePlugin.py"...
9820 INFO: Excluding import 'tkinter'
9821 INFO: Excluding import 'FixTk'
9859 INFO: checking Tree
9859 INFO: Building Tree because Tree-02.toc is non existent
9859 INFO: Building Tree Tree-02.toc
9864 INFO: Looking for ctypes DLLs
9884 INFO: Analyzing run-time hooks ...
9897 INFO: Looking for dynamic libraries
10940 INFO: Looking for eggs
10940 INFO: Using Python library /Library/Frameworks/Python.framework/Versions/3.7/Python
10952 INFO: Warnings written to /Users/development/git/my/gooey_test/build/widget_demo/warn-widget_demo.txt
11000 INFO: Graph cross-reference written to /Users/development/git/my/gooey_test/build/widget_demo/xref-widget_demo.html
11019 INFO: checking PYZ
11019 INFO: Building PYZ because PYZ-00.toc is non existent
11019 INFO: Building PYZ (ZlibArchive) /Users/development/git/my/gooey_test/build/widget_demo/PYZ-00.pyz
11598 INFO: Building PYZ (ZlibArchive) /Users/development/git/my/gooey_test/build/widget_demo/PYZ-00.pyz completed successfully.
11610 INFO: checking PKG
11611 INFO: Building PKG because PKG-00.toc is non existent
11611 INFO: Building PKG (CArchive) PKG-00.pkg
27800 INFO: Building PKG (CArchive) PKG-00.pkg completed successfully.
27811 INFO: Bootloader /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/PyInstaller/bootloader/Darwin-64bit/run_d
27811 INFO: checking EXE
27811 INFO: Building EXE because EXE-00.toc is non existent
27811 INFO: Building EXE from EXE-00.toc
27811 INFO: Appending archive to EXE /Users/development/git/my/gooey_test/dist/widget_demo
27880 INFO: Fixing EXE for code signing /Users/development/git/my/gooey_test/dist/widget_demo
27885 INFO: Building EXE from EXE-00.toc completed successfully.
27892 INFO: checking BUNDLE
27893 INFO: Building BUNDLE because BUNDLE-00.toc is non existent
27893 INFO: Building BUNDLE BUNDLE-00.toc
27974 INFO: moving BUNDLE data files to Resource directory
Daniels-MacBook-Air:gooey_test development$
```

**Running the application**

```
Daniels-MacBook-Air:gooey_test development$ dist/widget_demo
[16176] PyInstaller Bootloader 3.x
[16176] LOADER: executable is /Users/development/git/my/gooey_test/dist/widget_demo
[16176] LOADER: homepath is /Users/development/git/my/gooey_test/dist
[16176] LOADER: _MEIPASS2 is NULL
[16176] LOADER: archivename is /Users/development/git/my/gooey_test/dist/widget_demo
[16176] LOADER: Extracting binaries
[16176] LOADER: Executing self as child
[16176] LOADER: set _MEIPASS2 to /var/folders/lv/t4393j6n46sf69z_s2mmg6240000gp/T/_MEI4mpbnW
[16176] LOADER: Registering signal handlers
[16177] PyInstaller Bootloader 3.x
[16177] LOADER: executable is /Users/development/git/my/gooey_test/dist/widget_demo
[16177] LOADER: homepath is /Users/development/git/my/gooey_test/dist
[16177] LOADER: _MEIPASS2 is /var/folders/lv/t4393j6n46sf69z_s2mmg6240000gp/T/_MEI4mpbnW
[16177] LOADER: archivename is /Users/development/git/my/gooey_test/dist/widget_demo
[16177] LOADER: Already in the child - running user's code.
[16177] LOADER: Python library: /var/folders/lv/t4393j6n46sf69z_s2mmg6240000gp/T/_MEI4mpbnW/Python
[16177] LOADER: Loaded functions from Python library.
[16177] LOADER: Manipulating environment (sys.path, sys.prefix)
[16177] LOADER: sys.prefix is /var/folders/lv/t4393j6n46sf69z_s2mmg6240000gp/T/_MEI4mpbnW
[16177] LOADER: Pre-init sys.path is /var/folders/lv/t4393j6n46sf69z_s2mmg6240000gp/T/_MEI4mpbnW/base_library.zip:/var/folders/lv/t4393j6n46sf69z_s2mmg6240000gp/T/_MEI4mpbnW
[16177] LOADER: Setting runtime options
[16177] LOADER: Initializing python
[16177] LOADER: Overriding Python's sys.path
[16177] LOADER: Post-init sys.path is /var/folders/lv/t4393j6n46sf69z_s2mmg6240000gp/T/_MEI4mpbnW/base_library.zip:/var/folders/lv/t4393j6n46sf69z_s2mmg6240000gp/T/_MEI4mpbnW
[16177] LOADER: Setting sys.argv
[16177] LOADER: setting sys._MEIPASS
[16177] LOADER: importing modules from CArchive
[16177] LOADER: extracted struct
[16177] LOADER: callfunction returned...
[16177] LOADER: extracted pyimod01_os_path
[16177] LOADER: callfunction returned...
[16177] LOADER: extracted pyimod02_archive
[16177] LOADER: callfunction returned...
[16177] LOADER: extracted pyimod03_importers
[16177] LOADER: callfunction returned...
[16177] LOADER: Installing PYZ archive with Python modules.
[16177] LOADER: PYZ archive: PYZ-00.pyz
[16177] LOADER: Running pyiboot01_bootstrap.py
[16177] LOADER: Running widget_demo.py
Writing Build Config to: /Users/development/git/my/gooey_test/gooey_config.json
This program needs access to the screen. Please run with a
Framework build of python, and only when you are logged in
on the main display of your Mac.
[16176] LOADER: Restoring signal handlers
[16176] LOADER: freeing args
[16176] LOADER: returning child exit status 1
[16176] LOADER: Back to parent (RC: 1)
[16176] LOADER: Doing cleanup
[16176] LOADER: Freeing archive status for /Users/development/git/my/gooey_test/dist/widget_demo
```

**PyInstaller spec file**
 
```
 Daniels-MacBook-Air:gooey_test development$ cat widget_demo.spec
# -*- mode: python -*-
import gooey
gooey_root = os.path.dirname(gooey.__file__)
gooey_languages = Tree(os.path.join(gooey_root, 'languages'), prefix = 'gooey/languages')
gooey_images = Tree(os.path.join(gooey_root, 'images'), prefix = 'gooey/images')

block_cipher = None
import sys
sys.modules['FixTk'] = None


a = Analysis(['widget_demo.py'],
             pathex=['/Users/development/git/my/gooey_test'],
             binaries=[],
             datas=[],
             hiddenimports=['wx', 'gooey'],
             hookspath=[],
             runtime_hooks=[],
             excludes=['FixTk', 'tcl', 'tk', '_tkinter', 'tkinter', 'Tkinter'],
             win_no_prefer_redirects=False,
             win_private_assemblies=False,
             cipher=block_cipher,
             noarchive=False)
pyz = PYZ(a.pure, a.zipped_data,
             cipher=block_cipher)
exe = EXE(pyz,
          a.scripts,
          a.binaries,
          a.zipfiles,
          a.datas,
          [],
          gooey_languages,
          gooey_images,
          name='widget_demo',
          debug=True,
          bootloader_ignore_signals=False,
          strip=False,
          upx=True,
          runtime_tmpdir=None,
          console=True )
app = BUNDLE(exe,
             name='widget_demo.app',
             icon=None,
             bundle_identifier=None)
```

[widget_demo.spec.zip](https://github.com/chriskiehl/Gooey/files/2565576/widget_demo.spec.zip)

**Comment by chriskiehl** [comment] 2018-11-09 17:22
This is a partial duplicate of #259. I'm going to close this one and link it in the other thread so all these OSX "screen access" issues are grouped together.  I'll respond in that thread.

**Closed by chriskiehl** 2018-11-09 17:22 UTC

**Comment by engdan77** [comment] 2018-11-09 18:39
Thank you @chriskiehl for such fast feedback, it was indeed a good resource reading "PyInstaller FAQ" that very closely relates to the same symptom that I've been seeing. Even though as I've been generating this "freezed" version by using as below this on a Macbook only while using built-in display it gives this error.

```
python3 -m PyInstaller -F --windowed widget_demo.spec
```

What makes me wonder is that if I follow the exact same steps but instead in a folder create an wx_test.py with the following code

```
import wx
class Frame(wx.Frame):
    def __init__(self, title):
        wx.Frame.__init__(self, None, title=title, size=(350,200))
app = wx.App(redirect=True)
top = Frame("Hello World")
top.Show()
app.MainLoop()
```

It'll generate a package that you could run either as "dist/wx_test" or "open dist/wx_test.app" and this works without any warnings or issues. While doing the same but instead using widget_demo.py together with this widget_demo.spec (this needed to include e.g. images + languages) it would give this "This program needs access to the screen".

Also, obviously there is no issues with neither widget_demo.py (proven when running by "python3 ./widget_demo.py" works perfectly fine), nor PyInstaller since that works perfectly find when packaging wx_test.py. And my understanding was that Gooey uses wx as framework so can't wrap my head around why it would work with this simplified wx_test.py but not widget_demo.py .. 

But it is correct that while I was also (one of the many approaches) originally used pyenv I learned that you had to install the python-interpreter using this "--include-framework" and also tested anaconda which I also learned that if you wanted to run widget_demo.py you had to to use pythonw instead that I think must have answered @mrosewell issue he had.

I am very impressed by the simplicity of Gooey and also that it looks that good so I would be happy to do what I can to help "triage" this. I've spent a couple of days searching internet for others in the same spot which I would not find that unlikely - but the few I've seen are quite old and been using Python2 .. that is why I also now tested the same from another Mac OS 10.13 (High Sierra) using older Python 3.5.4 (installed from Mac binaries from www.python.org) in the hope of that it would make a difference but unfortunately not.

Thanks again ...
