### ISSUE TITLE
Question, catching a forced stop?

### ISSUE THREAD

**Issue by MrSassyBritches** [chriskiehl/Gooey#723] opened 2021-07-20 20:30 UTC
- [x] OS - **Windows 10**
 - [x] Python Version **CPython 3.7**
 - [x] Gooey Version **1.0.8.1**

How can I know if the user has clicked "Stop"?
My program now has a new specification, if the user cancels the process prematurely, it must be recorded. I see Iam able to specify a forced stop to be an error, is there any way to catch that?

this isn't an example, because I don't know what that would look like, but I hope this explains what I am hoping to accomplish just before the program exits.

```python
@gooey
def main():
    parser = GooeyParser(description="nit_validation")
	... arguments ...
    com_group.add_argument(
        "--display",
        metavar="Display COM port",
        default=settings["comports"]["display"],
    )
    args = parser.parse_args()
    print()
    print(args)
    print()
    burn_in = BurnInThread(
        debug_file_path=args.debug_file_path,
        exit_on_fail=args.exit_on_fail,
        host=args.host,
        aux=args.aux,
        front=args.front,
        display=args.display,
        serial_number=args.serial,
    )
	
	# do things!
    results = burn_in.burn_in(args.hours, args.delay)
    time.sleep(2)

	# program is about to exit, was is "stopped" or did it finish?

if __name__ == "__main__":
    main()

```

**Comment by chriskiehl** [comment] 2021-07-22 21:55
So, currently there's no way for you to detect the stop message coming from Gooey inside of your application code. The problem is that Gooey sends a [`SIGKILL`](https://docs.python.org/3/library/subprocess.html#subprocess.Popen.kill) to your process, which, by design, cannot be caught at the application level. 

There's a item in the backlog for [making the current behavior configurable](https://github.com/chriskiehl/Gooey/issues/232). For instance, sending a shutdown signal which could be caught by your application and dealt with appropriately. 

Do you need to take an immediate action when the user stops, or do you just need to be able to _discover_ that it was stopped at a later run? If the former, you're outta luck until the above issue gets implemented. If the latter, maybe you could get by with some type of journaling like databases do? If you persist some data as you go, you'll always be able to tell on the _next_ run whether or not the previous run was successful. Don't know if that's applicable to what you're doing or not, but throwing it out as a "thinking out loud" idea : ) 

Closing. Will prioritize #232

**Closed by chriskiehl** 2021-07-22 21:55 UTC

**Comment by chriskiehl** [comment] 2021-08-05 03:18
Hey @MrSassyBritches, I've added the ability to customize the stop strategy to the release branch. This'll let you catch when Gooey is doing a force stop. Wanna give it try and let me know if you hit any issues? Getting the signals sorted out on Windows took a fair bit of fiddling, so I'd love to hear if you run into any problems. 

Branch: https://github.com/chriskiehl/Gooey/tree/1.0.9-release

You can checkout the docs here: https://github.com/chriskiehl/Gooey/blob/1.0.9-release/docs/Gracefully-Stopping.md 

tl;dr: you can now pass a `signal` to the gooey decorator. 

```python
import signal 
@Gooey(shutdown_signal=signal.CTRL_C_EVENT)
def main(): 
   ...
```
