### ISSUE TITLE
Cannot concatenate list and tuple in dropdown.py

### ISSUE THREAD

**Issue by finsberg** [chriskiehl/Gooey#390] opened 2019-03-11 12:41 UTC
Hello 

I get the following error when trying to run gooey 

```
File "/Users/henriknf/local/src/Gooey/gooey/python_bindings/gooey_parser.py", line 113, in parse_args
    return self.parser.parse_args(args, namespace)
  File "/Users/henriknf/local/src/Gooey/gooey/python_bindings/gooey_decorator.py", line 78, in run_gooey
    application.run(build_spec)
  File "/Users/henriknf/local/src/Gooey/gooey/gui/application.py", line 15, in run
    app = build_app(build_spec)
  File "/Users/henriknf/local/src/Gooey/gooey/gui/application.py", line 24, in build_app
    gapp = GooeyApplication(merge(build_spec, imagesPaths))
  File "/Users/henriknf/local/src/Gooey/gooey/gui/containers/application.py", line 40, in __init__
    self.configs = self.buildConfigPanels(self)
  File "/Users/henriknf/local/src/Gooey/gooey/gui/containers/application.py", line 206, in buildConfigPanels
    for widgets in self.buildSpec['widgets'].values()]
  File "/Users/henriknf/local/src/Gooey/gooey/gui/containers/application.py", line 206, in <listcomp>
    for widgets in self.buildSpec['widgets'].values()]
  File "/Users/henriknf/local/src/Gooey/gooey/gui/components/config.py", line 15, in __init__
    self.layoutComponent()
  File "/Users/henriknf/local/src/Gooey/gooey/gui/components/config.py", line 80, in layoutComponent
    self.makeGroup(self, sizer, item, 0, wx.EXPAND)
  File "/Users/henriknf/local/src/Gooey/gooey/gui/components/config.py", line 119, in makeGroup
    widget = self.reifyWidget(parent, item)
  File "/Users/henriknf/local/src/Gooey/gooey/gui/components/config.py", line 159, in reifyWidget
    return widgetClass(parent, item)
  File "/Users/henriknf/local/src/Gooey/gooey/gui/components/widgets/bases.py", line 53, in __init__
    self.widget = self.getWidget(self)
  File "/Users/henriknf/local/src/Gooey/gooey/gui/components/widgets/dropdown.py", line 16, in getWidget
    choices=[default] + self._meta['choices'],
TypeError: can only concatenate list (not "tuple") to list
```

This can be fixed by forcing ` self._meta['choices']` to be a list when passed to `choices` in dropdown.py. Will submit a pull request for this.

 - Mac OS Mojave
 - Python 3.7.1 (pythonw)
 - Gooey Version 1.0.2
 
Best,
Henrik

**Comment by finsberg** [comment] 2019-03-11 12:47
Pull request [here](https://github.com/chriskiehl/Gooey/pull/391)

**Comment by chriskiehl** [comment] 2019-03-12 03:32
Could you provide a code sample that demos the problem? 

This sounds like an `argparse_to_json` problem. The `can only concatenate list (not "tuple")` issue is a downstream symptom of non-primitive (json) data getting into in the `buildspec`. So, in short, its a data sanitation issue in the bindings layer.

**Comment by finsberg** [comment] 2019-03-12 07:34
Yes, you are right that you can capture this in `argparse_to_json`. The error comes when you have an argument with choices where choices are a tuple. So this code throws an exception

```python
# issue.py
from gooey import Gooey, GooeyParser

@Gooey()
def main():
    parser = GooeyParser(description='Process some integers.')

    parser.add_argument(
        "--arg1",
        action="store",
        default="c1",
        choices=("c1", "c2", "c3"),
    )

    args = parser.parse_args()


if __name__ == '__main__':
    main()
```

Output:
```
Traceback (most recent call last):
  File "issue.py", line 20, in <module>
    main()
  File "/Users/henriknf/miniconda3/lib/python3.7/site-packages/Gooey-1.0.2-py3.7.egg/gooey/python_bindings/gooey_decorator.py", line 83, in inner2
    return payload(*args, **kwargs)
  File "issue.py", line 16, in main
    args = parser.parse_args()
  File "/Users/henriknf/miniconda3/lib/python3.7/site-packages/Gooey-1.0.2-py3.7.egg/gooey/python_bindings/gooey_parser.py", line 113, in parse_args
    return self.parser.parse_args(args, namespace)
  File "/Users/henriknf/miniconda3/lib/python3.7/site-packages/Gooey-1.0.2-py3.7.egg/gooey/python_bindings/gooey_decorator.py", line 78, in run_gooey
    application.run(build_spec)
  File "/Users/henriknf/miniconda3/lib/python3.7/site-packages/Gooey-1.0.2-py3.7.egg/gooey/gui/application.py", line 15, in run
    app = build_app(build_spec)
  File "/Users/henriknf/miniconda3/lib/python3.7/site-packages/Gooey-1.0.2-py3.7.egg/gooey/gui/application.py", line 24, in build_app
    gapp = GooeyApplication(merge(build_spec, imagesPaths))
  File "/Users/henriknf/miniconda3/lib/python3.7/site-packages/Gooey-1.0.2-py3.7.egg/gooey/gui/containers/application.py", line 40, in __init__
    self.configs = self.buildConfigPanels(self)
  File "/Users/henriknf/miniconda3/lib/python3.7/site-packages/Gooey-1.0.2-py3.7.egg/gooey/gui/containers/application.py", line 206, in buildConfigPanels
    for widgets in self.buildSpec['widgets'].values()]
  File "/Users/henriknf/miniconda3/lib/python3.7/site-packages/Gooey-1.0.2-py3.7.egg/gooey/gui/containers/application.py", line 206, in <listcomp>
    for widgets in self.buildSpec['widgets'].values()]
  File "/Users/henriknf/miniconda3/lib/python3.7/site-packages/Gooey-1.0.2-py3.7.egg/gooey/gui/components/config.py", line 15, in __init__
    self.layoutComponent()
  File "/Users/henriknf/miniconda3/lib/python3.7/site-packages/Gooey-1.0.2-py3.7.egg/gooey/gui/components/config.py", line 80, in layoutComponent
    self.makeGroup(self, sizer, item, 0, wx.EXPAND)
  File "/Users/henriknf/miniconda3/lib/python3.7/site-packages/Gooey-1.0.2-py3.7.egg/gooey/gui/components/config.py", line 119, in makeGroup
    widget = self.reifyWidget(parent, item)
  File "/Users/henriknf/miniconda3/lib/python3.7/site-packages/Gooey-1.0.2-py3.7.egg/gooey/gui/components/config.py", line 159, in reifyWidget
    return widgetClass(parent, item)
  File "/Users/henriknf/miniconda3/lib/python3.7/site-packages/Gooey-1.0.2-py3.7.egg/gooey/gui/components/widgets/bases.py", line 53, in __init__
    self.widget = self.getWidget(self)
  File "/Users/henriknf/miniconda3/lib/python3.7/site-packages/Gooey-1.0.2-py3.7.egg/gooey/gui/components/widgets/dropdown.py", line 16, in getWidget
    choices=[default] + self._meta['choices'],
TypeError: can only concatenate list (not "tuple") to list
```

I have created a new pull request [here](https://github.com/chriskiehl/Gooey/pull/394)

**Comment by chriskiehl** [comment] 2019-03-17 00:59
Upon closer inspection, this is a dupe of https://github.com/chriskiehl/Gooey/issues/312. 

It was fixed [here](https://github.com/chriskiehl/Gooey/commit/edf96bfe619b36b376535aed0c758ddeba5a613f). It'll be included in the next release.

**Closed by chriskiehl** 2019-03-17 00:59 UTC
