### ISSUE TITLE
Mutually Exclusive Group - do not select anything by default

### ISSUE THREAD

**Issue by tomasgreif** [chriskiehl/Gooey#693] opened 2021-05-06 12:49 UTC
In the docs section there is Mutually Exclusive Group with picture that shows no option selected. I am unable to achieve the same result by running `widget_demo`. The first option gets always selected.

 - [x] OS Ubuntu 20.04
 - [x] Python Version Python 3.8.5
 - [x] Gooey Version  1.0.8
 - [x] Thorough description of problem 
     - [ ] Expected: Nothing is selected by default for mutually exclusive group
     - [ ] First option is selected by default
 - [x] A minimal code example (below)

```
from gooey import Gooey, GooeyParser
from message import display_message


@Gooey(dump_build_config=True, program_name="Widget Demo")
def main():
    desc = "Example application to show Gooey's various widgets"
    file_help_msg = "Name of the file you want to process"
    my_cool_parser = GooeyParser(description=desc)
    verbosity = my_cool_parser.add_mutually_exclusive_group(required=False)
    verbosity.add_argument('-t', '--verbozze', dest='verbose',
                           action="store_true", help="Show more details")
    verbosity.add_argument('-q', '--quiet', dest='quiet',
                           action="store_true", help="Only output on error")

    my_cool_parser.parse_args()
    display_message()

def here_is_more():
    pass
if __name__ == '__main__':
    main()
```

**Comment by chriskiehl** [comment] 2021-05-19 03:35
This is a duplicate of https://github.com/chriskiehl/Gooey/issues/604. Checkout that issue for the full background, but the tl;dr: radio group behavior is dictated by your underlying OS / UI kit. For instance, on linux [GTK doesn't accept Radio Groups with nothing selected as valid](https://trac.wxwidgets.org/ticket/12344).

**Closed by chriskiehl** 2021-05-19 03:35 UTC
Labels: answered
