### ISSUE TITLE
docopt compatibility

### ISSUE THREAD

**Issue by tschinz** [chriskiehl/Gooey#187] opened 2017-03-13 16:36 UTC
Any intentions supporting docopt? 
https://github.com/docopt/docopt

Thanks for the great tool, hopefully it will be working also with python3 (damn wx ;-))

**Comment by chriskiehl** [comment] 2018-01-28 02:25
closing. Duplicate of #4 

(Gooey now works with Python3 now, btw ^_^ )

**Closed by chriskiehl** 2018-01-28 02:25 UTC
