### ISSUE TITLE
not possible to enter data if option is part of a mutually exclusive group

### ISSUE THREAD

**Issue by aatwork** [chriskiehl/Gooey#223] opened 2017-10-11 11:11 UTC
update: apparently those issues have already been reported but not fixed.

Please have a look at this buggy example (tested with Gooey installed via pip).

`from gooey import Gooey, GooeyParser
import argparse

@Gooey
def main():
    parser = GooeyParser()

    group = parser.add_mutually_exclusive_group(required=True)

    group.add_argument('--directory',
                       help="directory with infiles",
                       widget='DirChooser'
                       )
    group.add_argument('--infile',
                       type=argparse.FileType('r'),
                       help="single infile",
                       widget='FileChooser'
                       )

    parser.add_argument('--outfile',
                        type=argparse.FileType('w'),
                        help="output file",
                        required=True,
                        widget='FileSaver'
                        )

    return parser.parse_args()

if __name__ == '__main__':
    main()
`
1) There is no possibility to select arguments for --infile and --directory (see issue #208)
2) required arguments are moved to the optional section (see issue #215 )

![notrack_gooey_issue](https://user-images.githubusercontent.com/28901114/31437573-0748fce0-ae86-11e7-8def-e08adc1b3f74.png)

**Comment by chriskiehl** [comment] 2017-10-15 23:10
Duplicate of #208

**Closed by chriskiehl** 2017-10-15 23:10 UTC
