### ISSUE TITLE
Bug in counter formatting?

### ISSUE THREAD

**Issue by TristanRollond** [chriskiehl/Gooey#322] opened 2018-09-21 04:43 UTC
- Windows 10
 - 3.6
 - Unsure
 - I created a counter argument, but after having a look, it seems there is a typo in the formatting file.
 - def counter(metadata, value):
    '''
    Returns
      str(option_string * DropDown Value)
      e.g.
      -vvvvv
    '''
    if not str(value).isdigit():
        return None
    arg = str(metatdata['commands'][0]).replace('-', '')
    repeated_args = arg * int(value)
    return '-' + repeated_args
 - I think that is should be metadata not metatdata. I cannot edit this myself to test as it says I don't have permission.
 

Thanks! ^_^

**Comment by chriskiehl** [comment] 2018-09-22 18:51
The is a dupe of #316 - it's been fixed here https://github.com/chriskiehl/Gooey/commit/d37508da77a24b2a876436fc33cf767a56d17ce5 

It'll be in the next release ^_^

**Closed by chriskiehl** 2018-09-22 18:51 UTC

**Comment by TristanRollond** [comment] 2018-09-24 00:38
Um, sorry, I don't know what I am supposed to with the file.

**Comment by chriskiehl** [comment] 2018-09-24 16:07
You can either (a) [pip install the branch](https://stackoverflow.com/questions/20101834/pip-install-from-git-repo-branch) to get a sneak peak / test / give feedback, or (b) wait for the official release.
