### ISSUE TITLE
Unable to take multiple files as input

### ISSUE THREAD

**Issue by JauntyJJS** [chriskiehl/Gooey#260] opened 2018-02-20 09:08 UTC
Hi

I am running on Windows 10, python 3.6.4 64bit, Gooey version 1.0.0

It seems the recent version of Gooey no longer has the options to accept multiple file inputs.
Perhaps it is still under development till further notice.

When I set the widget as 'MultiFileChooser'

![image](https://user-images.githubusercontent.com/9066508/36415149-bff42f1c-165f-11e8-98b4-ed6b3b2afa82.png)

The code still runs but I can only upload one file

To resolve this, I change the chooser.py script in \gooey\gui\components\widgets\core

Around line 68 change 
```
class MultiFileChooser(Chooser):
    """ Retrieve an multiple files from the system """
    def getDialog(self):
        return wx.FileDialog(self, style=wx.FD_OPEN | wx.FD_FILE_MUST_EXIST)
```
 to

```
class MultiFileChooser(Chooser):
    """ Retrieve an multiple files from the system """
    def getDialog(self):
        return wx.FileDialog(self, "Open Files" ,style=wx.FD_OPEN | wx.FD_FILE_MUST_EXIST | wx.FD_MULTIPLE)
    def getResult(self, dialog):
        return os.pathsep.join(dialog.GetPaths()) 
```

This ensures that multiple file paths are separated by semi colon in the input text box.

Hope this helps.

Regards,
Jeremy

**Comment by chriskiehl** [comment] 2018-02-20 16:56
Hey @JauntyJJS, good catch! Looks like you've already root caused the issue. Would you mind making a pull request with that change? ^_^

**Comment by JauntyJJS** [comment] 2018-02-21 07:00
Hi,

I have made a pull request in https://github.com/chriskiehl/Gooey/pull/263/files
Please check that everything is fine.

Regards,
Jeremy

**Comment by chriskiehl** [comment] 2018-02-21 18:19
👍 I'll check it out tonight!

**Comment by JauntyJJS** [comment] 2018-02-22 01:00
So sorry but I forgot to add the 
```
import os 
```
at the top of the code.

Do I need to create another pull request ?

**Comment by bilderbuchi** [comment] 2018-02-22 05:41
You can just add another commit to your pull request's branch, push that, and the or will be updated. :-)

**Comment by bilderbuchi** [comment] 2018-02-22 05:41
or -> PR

**Comment by JauntyJJS** [comment] 2018-02-22 14:47
Ok. I have made the change.

**Comment by chriskiehl** [comment] 2018-02-27 03:51
nice work! Merged!

**Closed** 2018-02-27 03:51 UTC

**Comment by jni** [comment] 2018-05-08 09:25
@chriskiehl not a big blocker since it's easy to install from source, but, think you wanna cut a release with this fix? ;)

**Comment by spot92** [comment] 2019-12-14 02:25
Is it possible to change it so that the files are separated by a comma and not a semi colon?
