### ISSUE TITLE
Does not read "required" option

### ISSUE THREAD

**Issue by nsaunier** [chriskiehl/Gooey#80] opened 2015-04-01 09:28 UTC
Hi,

I have a program with 4 options, only one is required. But the GUI keeps asking to fill values for all options, or it makes an error when clicking on start. 

`usage: tmpj1yUVg.py [-h] -i VIDEOFILENAME [-f FIRSTFRAMENUM] [--fps FRAMERATE]
                    [-r RESCALE]
tmpj1yUVg.py: error: argument -f: expected one argument`

Also, it repeats the one required option in both the "Required arguments" and Optional arguments parts of the GUI. 

This is on Ubuntu 14.04 with python 2.7.6.

Thanks!

Nicolas

**Comment by chriskiehl** [comment] 2015-04-01 12:41
This is a duplicate of Issue #78. Twas fixed awhile ago. You may be on a slightly old version. If you clone a fresh copy of the repo, you should be good to go.

**Closed by chriskiehl** 2015-04-01 12:41 UTC

**Comment by nsaunier** [comment] 2015-04-01 12:51
Sorry, but I took the version through pip: is it not up to date?

**Comment by chriskiehl** [comment] 2015-04-01 12:54
Ahh... yeah, that's one is probably a few versions behind. I should really add a git hook to keep that thing updated. Apologies for the confusion.
