### ISSUE TITLE
Required arguments shown as optional

### ISSUE THREAD

**Issue by ATran31** [chriskiehl/Gooey#447] opened 2019-06-06 15:26 UTC
I see you fixed this years ago in #78 but for some reason I am having this problem still. I'm using Gooey 1.0.2 on Python 3.6.8, Windows 7. I initially installed from pip and then tried to correct the issue by cloning the repo. Same result both cases.
My argument definitions:

![image](https://user-images.githubusercontent.com/8496965/59044456-291a6b00-884c-11e9-8c83-8d2b0ad7ed43.png)

![Capture1](https://user-images.githubusercontent.com/8496965/59044253-d476f000-884b-11e9-9a4d-3d5f420bed5c.PNG)

**Comment by eladeyal-intel** [comment] 2019-06-06 19:05
Here is code to reproduce:
```
from gooey import Gooey, GooeyParser
@Gooey
def main():
    p=GooeyParser()
    p.add_argument('-s',required=True, widget='FileChooser')
    p.add_argument('-l',widget='DirChooser')
    p.parse_args()
if __name__=='__main__':
    main()
```

It still exists on 1.0.3-release as well.

However, note that the arguments are not treated as optional; it's only the title "optional argument" which bothers you.

As a workaround, you can create a single argument_group (optionally name it.)

like this:
```
from gooey import Gooey, GooeyParser
@Gooey
def main():
    p=GooeyParser()
    g=p.add_argument_group()
    g.add_argument('-s',required=True, widget='FileChooser')
    g.add_argument('-l',widget='DirChooser')
    p.parse_args()
if __name__=='__main__':
    main()
```

**Comment by ATran31** [comment] 2019-06-07 13:29
Thanks. I have created required and optional group as a workaround.

**Comment by chriskiehl** [comment] 2019-06-14 03:14
Yeah, this comes up a lot. I need to add a FAQ and updated the README. short answer: this is by design. Longer answer on this issue: https://github.com/chriskiehl/Gooey/issues/368 

Summary version: The original required/optional split in Gooey was a bad choice and doesn't make sense now that there are first class argument groups. Meaning, there isn't necessarily a top level 'required' group into which you can reliably put everything marked as `required` _while still_ honoring argument groups. They're exclusive ideas.

**Closed by chriskiehl** 2019-06-14 03:14 UTC
