### ISSUE TITLE
Gooey-fied script that has a dependency on another script with an @Gooey annotation causes infinite setup-screen workflow

### ISSUE THREAD

**Issue by gRichardson108** [chriskiehl/Gooey#458] opened 2019-07-22 01:04 UTC
- [X] OS - Fedora 29 x86_64
 - [X] Python Version - Python 3.7.3 (From miniconda)
 - [X] Gooey Version - 1.0.2
 - [X] When Gooey-fied script imports a value from another script that also has an `@Gooey` annotation *anywhere in that script*, the GUI in the first script will endlessly loop back to the setup page when "next" is pressed, and never run.
     - [X] Expected Behavior: When `python MainScript.py` is run, it will take the user-input "ResourceNumber", and print the corresponding value from the list imported from "ResourceScript". 
     - [X] Actual Behavior: The Gooey setup screen for MainScript.py's argument displays. When a value is entered and "next" is pressed, the window switches to the "running" screen, but then *another* setup screen for MainScript.py appears. If you enter an argument and hit "next", it changes to an additional "running" screen, and *another* setup screen appears. I think you can do this endlessly.
 - [X] A minimal code example:
```python
#MainScript.py
import argparse
from gooey import Gooey
from ResourceScript import ConstantArray

def get_resource(num):
    return ConstantArray[num]

@Gooey
def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("ResourceNumber")
    args = parser.parse_args()

    print(get_resource(int(args.ResourceNumber)))

if __name__=="__main__":
    main()
```
```python
#ResourceScript.py
import argparse
from gooey import Gooey

ConstantArray = [
        'foo',
        'bar',
        'baz',
        'gat'
]

# Doesn't matter what this does, as long as there's another Gooey-annotated function
@Gooey
def main():
    parser = arparse.ArgumentParser()
    parser.add_argument("echo")
    args = parser.parse_args()

    print(parser.echo)
    for c in ConstantArray:
        print(c)

if __name__=="__main__":
    main()
```

Save the two files `MainScript.py` and `ResourceScript.py` in the same directory, then run `python MainScript.py`. You will see the behavior described above. My real-world encounter with this was a little different, but this seems to reproduce it. I haven't dug into Gooey's code at all, although I imagine it has something to do with how the annotation is handled.

**Comment by chriskiehl** [comment] 2019-09-01 03:18
Neat.

The root of the problem is due to an interaction (a) the eager evaluation or decorators, and (b) the fact that Gooey and Argparse read from the global mutable state that is `sys.argv`. 

More background than is probably wanted, but when Gooey invokes your program, here's the flow: 

1. python begins parsing `MainScript.py`
2. hops into `ResourceScript.py` while resolving imports
3. Gooey decorator gets evaluated 
4. The internal `IGNORE_GOOEY` flag is popped out of `sys.argv` so that it doesn't show up in your code
5. parser returns to `MainScript.py`
6. `main`'s Gooey decorator gets evaluated
7. It finds no `IGNORE_GOOEY` flag (removed in step 4), and thus thinks it needs to show the UI again

Thus you get an endless stream of initial Gooey configuration screens. 

This could potentially be worked around in Gooey, but, the lame answer is that hesitant to do so as, this is pretty niche (first time it has come up) and it would require some (more) crufty global state tracking to work around the already global modification of sys.argv (forced upon us by Argparse!). 

**The good news:**

You're not outta luck, though! ^_^ 

An easy fix to your specific problem would be to just "manually" decorate your non-main functions _after_ the `if __name__ == '__main__'` guards. This prevents them from being eagerly evaluated and the problem goes away! 

Here's an example: 

**main.py**

```python
import argparse
from gooey import Gooey
from examples.issue458.resource import ConstantArray

def get_resource(num):
    return ConstantArray[num]

@Gooey
def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("ResourceNumber")
    args = parser.parse_args()

    print(get_resource(int(args.ResourceNumber)))

if __name__ == "__main__":
    main()
```

**resource.py**

```python
import argparse
from gooey import Gooey

ConstantArray = [
        'foo',
        'bar',
        'baz',
        'gat'
]


def fooobar():
    parser = argparse.ArgumentParser()
    parser.add_argument("echo", help="sup fam")
    args = parser.parse_args()

    print(args)


if __name__ == "__main__":
    Gooey(fooobar)()   # <-- manually applying the decorator 
```

This lets you run main without endless Gooey instances and _still_ run other things in your project directly as well.

**Closed by chriskiehl** 2019-09-01 03:18 UTC
