### ISSUE TITLE
mutually exclusive group initial selection greyed out

### ISSUE THREAD

**Issue by frederikvs** [chriskiehl/Gooey#585] opened 2020-06-16 12:22 UTC
In the mutually_exclusive_group, we can pass an `initial_selection`, and it chooses the right radio button, but e.g. dropdowns and the like that should be enabled by that radio button are still greyed out.

I was building on the `dynamic_updates.py` example when I noticed this behavior. Minimal example : 

```
from gooey import Gooey, GooeyParser

@Gooey
def main():

    parser = GooeyParser(description="GUI")

    g = parser.add_argument_group()

    stuff = g.add_mutually_exclusive_group(
        required=True,
        gooey_options={
            'initial_selection': 0
        }
    )

    stuff.add_argument(
        '--filter',
        action='store',
    )

    stuff.add_argument(
        '--name',
        widget='Dropdown',
        choices=['foo', 'bar'],
    )

    args = parser.parse_args()


if __name__ == '__main__':
    main()

```

When you first start this, it looks like this : 
![behavior](https://user-images.githubusercontent.com/3795966/84773286-7b07dc00-afdc-11ea-80b6-3379ae30ef56.png)

I was expecting it to already give me the option to fill in something in that `filter` field, like below.

![expected](https://user-images.githubusercontent.com/3795966/84773191-5875c300-afdc-11ea-81df-8044428e3660.png)

(This screenshot was created by first clicking the `name` radio button, then the `filter` radio button again.

Happens on both MacOS and windows, both with gooey 1.0.3.1, python 3.

**Comment by chriskiehl** [comment] 2020-06-16 18:40
Duplicate of https://github.com/chriskiehl/Gooey/issues/517. This has been fixed on the release branch.

**Closed by chriskiehl** 2020-06-16 18:40 UTC
