### ISSUE TITLE
Index out of range (Subparser issue?)

### ISSUE THREAD

**Issue by ccann** [chriskiehl/Gooey#70] opened 2015-02-18 16:50 UTC
```
Traceback (most recent call last):
  File "lib/qidev.py", line 114, in <module>
    main()
  File "/usr/local/lib/python2.7/dist-packages/gooey/python_bindings/gooey_decorator.py", line 138, in inner
    frame = BaseWindow(BodyPanel, build_spec, params)
  File "/usr/local/lib/python2.7/dist-packages/gooey/gui/windows/base_window.py", line 36, in __init__
    self._init_components(BodyPanel)
  File "/usr/local/lib/python2.7/dist-packages/gooey/gui/windows/base_window.py", line 60, in _init_components
    self.config_panel = BodyPanel(self)
  File "/usr/local/lib/python2.7/dist-packages/gooey/gui/windows/advanced_config.py", line 39, in __init__
    self._do_layout()
  File "/usr/local/lib/python2.7/dist-packages/gooey/gui/windows/advanced_config.py", line 70, in _do_layout
    self.CreateComponentGrid(container, self.components.general_options, cols=2)
  File "/usr/local/lib/python2.7/dist-packages/gooey/gui/windows/advanced_config.py", line 90, in CreateComponentGrid
    hsizer.Add(widget.build(self), 1, wx.EXPAND | wx.LEFT | wx.RIGHT, 10)
  File "/usr/local/lib/python2.7/dist-packages/gooey/gui/widgets/components2.py", line 30, in build
    return self.do_layout(parent)
  File "/usr/local/lib/python2.7/dist-packages/gooey/gui/widgets/components2.py", line 38, in do_layout
    core_widget_set = self.widget_pack.build(self.panel, self.data)
  File "/usr/local/lib/python2.7/dist-packages/gooey/gui/widgets/widget_pack.py", line 141, in build
    self.option_string = data['commands'][0]
IndexError: list index out of range
```

If it's helpful for debugging, all of the code for `qidev.py` is available on [my github](https://github.com/ccann/qidev/blob/master/lib/qidev.py)

Distributor ID:	Ubuntu
Description:	Ubuntu 14.10
Release:	14.10
Codename:	utopic
Linux  3.16.0-30-generic #40-Ubuntu SMP Mon Jan 12 22:07:27 UTC 2015 i686 i686 i686 GNU/Linux

**Comment by chriskiehl** [comment] 2015-02-18 17:30
This is a duplicate of Issue #41 

Subparsers aren't currently supported. They're on my TODO. The initial hurdle is that I'm not totally sure how they'd be represented on the UI side. Tabs? Sliders? A new `page` type? I dunno. It'd take some brain storming to figure out how best to represent the different parser "paths."

**Comment by ccann** [comment] 2015-02-18 17:32
Okay, I thought it might be. Sorry for the dupe.

**Closed** 2015-02-18 17:31 UTC
Labels: duplicate

**Comment by chriskiehl** [comment] 2015-02-18 17:46
No worries. : )

**Comment by chriskiehl** [comment] 2015-05-27 02:07
Hey @ccann!

Would you mind if I used an excerpt from the code you posted above in the examples directory? Subparser support is almost finished!

**Comment by ccann** [comment] 2015-05-27 02:55
Sure thing

**Comment by chriskiehl** [comment] 2015-05-27 03:28
Awesome sauceum. Thanks!
