### ISSUE TITLE
Windows 10  - random window placement

### ISSUE THREAD

**Issue by sgnp** [chriskiehl/Gooey#451] opened 2019-06-27 01:37 UTC
The problem: Whenever I run Gooey (for example, any of the provided examples), the windows is placed in a different position. This is usually somewhere towards the left right part of the screen and different by a few pixels on each run.
It would be much nicer, if it where possible to center the window! Using the window_pos is of no help either since setting it =(0,0) neither places the screen in the center or the upper left corner, as would be expected. Running the code a few times with the same value for windos_pos will still make the screen appear at  different positions.

Setup:
Windows 10
Python 3.6.7
Gooey  1.02
wxPython 4.0.6

**Comment by chriskiehl** [comment] 2019-06-27 03:12
Howdy, 

This is a dupe of https://github.com/chriskiehl/Gooey/issues/302. Give that issue a read and see if it covers your use cases.

**Closed by chriskiehl** 2019-06-27 03:12 UTC

**Comment by sgnp** [comment] 2019-06-27 09:05
Please reopen. I had known about #302 and it does *not* cover my case. As I described above the window_pos setting does not work reliably.

**Comment by chriskiehl** [comment] 2019-06-27 15:38
There is no `window_pos` option in Gooey. It not existing may be the source of the "unreliability" you're encountering : ) 

Your issue, like #302, is a feature request, not a bug report. Unless there is something unique in your request that I'm misunderstanding and that isn't captured by the other issue (which it appears to be, center anchoring is specifically mentioned), we probably don't need two issues open for the same thing. I'd still encourage you to put your use cases under 302.
