### ISSUE TITLE
Minimal FileChooser example breaks on Ubuntu 14

### ISSUE THREAD

**Issue by thoppe** [chriskiehl/Gooey#82] opened 2015-04-02 17:05 UTC
Example code:

```
from gooey import Gooey
from gooey import GooeyParser

@Gooey(advanced=True)
def main(): 
    parser = GooeyParser(description="My Cool Gooey App!")
    parser.add_argument('filename', 
                        help="name of the file to process", 
                        widget='FileChooser') 
    parser.parse_args()

if __name__ == "__main__":
    main()
```

Traceback

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gooey/gui/widgets/widget_pack.py", line 82, in onButton
    self.text_box.SetLabelText(result)
AttributeError: 'TextCtrl' object has no attribute 'SetLabelText'
```

Using Ubuntu 14.10. Happy to provide any more information.

**Comment by thoppe** [comment] 2015-04-02 17:06
Example code:

```
from gooey import Gooey
from gooey import GooeyParser

@Gooey(advanced=True)
def main(): 
    parser = GooeyParser(description="My Cool Gooey App!")
    parser.add_argument('filename', 
                        help="name of the file to process", 
                        widget='FileChooser') 
    parser.parse_args()

if __name__ == "__main__":
    main()
```

Traceback

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gooey/gui/widgets/widget_pack.py", line 82, in onButton
    self.text_box.SetLabelText(result)
AttributeError: 'TextCtrl' object has no attribute 'SetLabelText'
```

**Comment by chriskiehl** [comment] 2015-04-02 17:48
I think you may be running an out of date version of Gooey. This is a duplicate of issue #76, which was fixed in commit d83ab61bff9c5. 

Try cloning a fresh copy of the repository (from git, not pip!) and you should be good to go. Feel free to reopen if the issue persists.

**Closed by chriskiehl** 2015-04-02 17:48 UTC

**Comment by thoppe** [comment] 2015-04-02 18:23
It works perfectly now! Sorry, you were correct, I was using the pip version. Thanks for making the library!

**Comment by chriskiehl** [comment] 2015-04-02 18:41
My fault for not keeping the pypi project up to date with the current state of the repo. 

I really need to figure out how to tie the two together. Out of date pip bites people all the time!
