### ISSUE TITLE
second add_mutually_exclusive_group is not treated as such

### ISSUE THREAD

**Issue by eladeyal-intel** [chriskiehl/Gooey#412] opened 2019-04-18 13:25 UTC
![image](https://user-images.githubusercontent.com/20379005/56364098-725c2000-61f6-11e9-9753-0ac4f330cb24.png)

```
from __future__ import print_function
from gooey import Gooey, GooeyParser as ArgumentParser

@Gooey()
def main():
    parser=ArgumentParser()
    g=parser.add_mutually_exclusive_group()
    g.add_argument('-a', action='store_true')
    g.add_argument('-b', action='store_true')
    g=parser.add_mutually_exclusive_group()
    g.add_argument('-c', action='store_true')
    g.add_argument('-d', action='store_true')
    print(parser.parse_args())        
    
if __name__ == '__main__':
    main()
```

 
 tested with v1.0.2 from pypi

**Comment by chriskiehl** [comment] 2019-04-18 15:50
Duplicate of https://github.com/chriskiehl/Gooey/pull/385 and https://github.com/chriskiehl/Gooey/pull/388

**Closed by chriskiehl** 2019-04-18 15:50 UTC
