### ISSUE TITLE
Listbox when selecting values, still giving the validation message.

### ISSUE THREAD

**Issue by mukeshoza** [chriskiehl/Gooey#356] opened 2018-12-05 07:43 UTC
**System Info**

 - MacOS, Version: 10.14
 - 3.7.1 Python Version 
 - 1.0.2 Gooey Version

**Issue**

 - While trying to select the values from Listbox, I am getting validation error as '**_The field is required_**' even though I have selected 2 values from the listbox.

**Sample Code:**

    filters.add_argument(
                        '--filteroption', choices=headers,
                             help='Select the column name you want to filter data for:',
                             widget='Listbox',
                             required=True,
                             nargs='*',
                             metavar='Select Column Name',
                             default='sku'

**Screenshot:**

![image](https://user-images.githubusercontent.com/18232678/49497553-cb9f6480-f890-11e8-9f8b-85071b1efc7e.png)

**Comment by gonzygonz** [comment] 2018-12-07 22:36
Hi,
as a workaround you can add a validator like this:
```
gooey_options={
            'validator': {
                'test': 'user_input != "Select Option"',
                'message': 'Choose a save file from the list'
            }
        }
```
also, i noticed you tried to add a default selection, but in listbox you should give a list of options, and not a string. so should be something like: `default=['sku']`

hope this at least helps you until this is fixed :)

**Comment by chriskiehl** [comment] 2018-12-08 03:08
This is fixed on the release branch here: https://github.com/chriskiehl/Gooey/tree/1.0.3-release 

Give it a spin and feel free to re-open if I got something wrong! 👍

**Comment by chriskiehl** [comment] 2019-01-30 04:57
Hey, could you provide an example where it is failing? 

The 'weird dict thing' is python's set literal, so the presence behaves exactly as a list would. 

```python
@Gooey
def main():
    parser = GooeyParser()
    parser.add_argument(
        "some_string",
        action="store",
        default="just press Start",
    )

    parser.add_argument(
        '--filteroption', choices=['sku', 'foo', 'bar'],
        help='Select the column name you want to filter data for:',
        widget='Listbox',
        required=True,
        nargs='*',
        metavar='Select Column Name',
        # default='sku'
    )
    parser.add_argument(
        '--filteroption2', choices=['sku', 'foo', 'bar'],
        help='Select the column name you want to filter data for:',
        widget='Listbox',
        required=True,
        nargs='*',
        metavar='Select Column Name',
        default='sku'
    )

    parser.add_argument(
        '--filteroption3', choices=['sku', 'foo', 'bar'],
        help='Select the column name you want to filter data for:',
        widget='Listbox',
        required=True,
        nargs='*',
        metavar='Select Column Name',
        default=['bar']
    )

    parser.add_argument(
        '--filteroption4', choices=['sku', 'foo', 'bar'],
        help='Select the column name you want to filter data for:',
        widget='Listbox',
        required=True,
        nargs='*',
        metavar='Select Column Name',
        default=['sku', 'foo']
    )

    parser.add_argument(
        '--dropdown1', choices=['sku', 'foo', 'bar'],
        help='Select the column name you want to filter data for:',
        required=True,
        nargs='*',
        metavar='Select Column Name',
    )

    parser.add_argument(
        '--dropdown2', choices=['sku', 'foo', 'bar'],
        help='Select the column name you want to filter data for:',
        required=True,
        nargs='*',
        metavar='Select Column Name',
        default='bar'
    )

    args = parser.parse_args()
    print(args, flush=True)

```

Have I missed a scenario?

**Comment by chriskiehl** [comment] 2019-03-10 05:11
Closing as I'm unable to reproduce on release branch.

**Closed by chriskiehl** 2019-03-10 05:11 UTC
