### ISSUE TITLE
Crash after run with latest upgrade

### ISSUE THREAD

**Issue by sousasag** [chriskiehl/Gooey#152] opened 2016-02-09 15:31 UTC
Hi, 

I installed gooey on a new machine. I also experienced the problem with the drop menus for the parameters. After upgrading a few minutes ago this was fix but now I got a crash end the main function ends:

Pango:ERROR:/build/buildd/pango1.0-1.36.8/./pango/pango-layout.c:3916:pango_layout_check_lines: assertion failed: (!layout->log_attrs)

The gooey window crashes completly before appearing the edit options. and then the system kills the process completly.

Any idea?

Thanks in advance,
Sérgio

**Comment by chriskiehl** [comment] 2016-02-09 15:33
Please give details 

platform/wx version/python version/script to reproduce

**Comment by sousasag** [comment] 2016-02-09 15:53
Ubuntu 15.10/
libwxgtk2.8-0:amd64                 2.8.12.1+dfsg2-2ubuntu amd64                  wxWidgets Cross-platform C++ GUI toolkit (GTK+ runtime)/
Python 2.7.10/

Simple Script:
```
'''
A minimal Gooey example. One required field, one optional.

'''


import argparse
from gooey import Gooey
from gooey import GooeyParser
import SPECPAR as sp
import os


@Gooey(program_name='SPECPAR - chain stellar parameters', default_size=(700, 1000), advanced=True, dump_build_config=True)
def main():
  parser = GooeyParser(description="SPECPAR GUI Chain Parameters!")	
  parser.add_argument('moog_version', help='Version of MOOG', default='2014', choices=['2013', '2014'], type=str, metavar='MOOG version')
  parser.add_argument('model'   , help='Model atmosphere',    default='KURUCZ', choices=['KURUCZ', 'MARCS'])

  args = parser.parse_args()
  print "Running SPECPAR may take several minutes..."
  print "Run and test..."



if __name__ == '__main__':
  main()

```

Error that I got in terminal:

```
python SPECPAR_Gooey_test.py 
Writing Build Config to: /home/sousasag/Programas/GIT_projects/SPECPAR/gooey_config.json
**
Pango:ERROR:/build/buildd/pango1.0-1.36.8/./pango/pango-layout.c:3916:pango_layout_check_lines: assertion failed: (!layout->log_attrs)
Aborted
```

**Comment by sousasag** [comment] 2016-02-09 19:31
Hi again,

Just some more info about this issue. I upgraded on my old computer with Ubuntu 14.04 LTS,
Python 2.7.6
libwx2.8: 2.8.12.1+dfsg-2ubuntu2

```
Writing Build Config to: /home/sousasag/Programas/GIT_projects/SPECPAR/gooey_config.json
**
Pango:ERROR:/build/buildd/pango1.0-1.36.3/./pango/pango-layout.c:3916:pango_layout_check_lines: assertion failed: (!layout->log_attrs)
Aborted
```

With the previous version of gooey 0.8.15.2 it was working fine...

**Comment by chris1610** [comment] 2016-02-10 21:02
FWIW, I am seeing the same issue. The same script runs fine on Windows but throws the pango layout error on Ubuntu.

I am running in an anaconda environment vs. the default ubuntu environment.

**Comment by chriskiehl** [comment] 2016-02-13 15:26
Blasted WX cross-platform wonkiness strikes again! Sorry for the troubles, guys! 

I haven't been able to reproduce the `Pango` error, but I do get a `fatal IO` error on my Ubuntu VM. However, from a bit of Googling, I suspect these are caused by the same core issue. Namely, it seems to be that a thread talking to bit of the program that it shouldn't. 

Investigating now.

**Comment by chriskiehl** [comment] 2016-02-13 16:31
@sousasag, @chris1610,

Could you guys give this branch a try for me? https://github.com/chriskiehl/Gooey/tree/linux-thread-safety

It seems to have definitely been a threading issue. I was able to reproduce the Pango error just by running multiple times in a row. It'd seem to hop back and forth between that one, a `Thread Queue error`, and a `Fatal IO` error. 

I feel like I've typed this message a million times now (soon I will take it to heart): Linux's WX build is super-duper finicky about the main GUI thread -- just setting the internal value on a widget from the secondary thread was causing the explosion. 

I hacked in a fix. Let me know if it resolves your issues.

**Comment by chris1610** [comment] 2016-02-15 03:35
I got around to testing this on my Linux system and it works for me. The issue I was having before is gone and everything else is working as expected.

Thanks for the quick fix.

**Comment by sousasag** [comment] 2016-02-15 10:57
Hi,

just tested the branch and seems to work perfectly once again.

Many thanks

**Comment by DanielAndreasen** [comment] 2016-02-15 13:02
Whit this comment, I can get an update when you close this and probably merge it :)

**Comment by bilderbuchi** [comment] 2016-02-15 15:39
@DanielAndreasen you could also just hit the "Subscribe" button on the right side of this webpage. :-)

**Comment by chriskiehl** [comment] 2016-02-16 00:28
This has been merged into master. 

Thanks for testing everyone! <sub><sup>(sorry for breaking things)</sup></sub>

**Closed by chriskiehl** 2016-02-16 00:28 UTC

**Comment by chris1610** [comment] 2016-02-16 00:44
Thanks for the quick response. This is a great project and I appreciate your work on it!
