### ISSUE TITLE
Gooey and Python2

### ISSUE THREAD

**Issue by Yanjo96** [chriskiehl/Gooey#286] opened 2018-04-25 15:42 UTC
Hey,

i am using Arch Linux with python version 2.7 and Gooey version 1.0.0 and it does not work. Your example codes are running for python 3 but unfortunately not with python2 even if wxpython is installed. The following is the error message that i get if i try to run your example codes with python2:

```
usr/lib/python2.7/site-packages/wx-3.0-gtk3/wx/_core.py:16629:
 UserWarning: wxPython/wxWidgets release number mismatch
  warnings.warn("wxPython/wxWidgets release number mismatch")
Traceback (most recent call last):
  File "../annonex2embl/scripts/annonex2embl_GUI_Gooey.py", line 152, in <module>
    main()
  File "/usr/lib/python2.7/site-packages/Gooey-1.0.0-py2.7.egg/gooey/python_bindings/gooey_decorator.py", line 83, in inner2
    return payload(*args, **kwargs)
  File "../annonex2embl/scripts/annonex2embl_GUI_Gooey.py", line 143, in main
    args = parser.parse_args()
  File "/usr/lib/python2.7/site-packages/Gooey-1.0.0-py2.7.egg/gooey/python_bindings/gooey_decorator.py", line 78, in run_gooey
    application.run(build_spec)
  File "/usr/lib/python2.7/site-packages/Gooey-1.0.0-py2.7.egg/gooey/gui/application.py", line 15, in run
    app = build_app(build_spec)
  File "/usr/lib/python2.7/site-packages/Gooey-1.0.0-py2.7.egg/gooey/gui/application.py", line 24, in build_app
    gapp = GooeyApplication(merge(build_spec, imagesPaths))
  File "/usr/lib/python2.7/site-packages/Gooey-1.0.0-py2.7.egg/gooey/gui/containers/application.py", line 39, in __init__
    self.header = FrameHeader(self, buildSpec)
  File "/usr/lib/python2.7/site-packages/Gooey-1.0.0-py2.7.egg/gooey/gui/components/header.py", line 33, in __init__
    self.layoutComponent()
  File "/usr/lib/python2.7/site-packages/Gooey-1.0.0-py2.7.egg/gooey/gui/components/header.py", line 60, in layoutComponent
    self.settings_img = self._load_image(images['configIcon'], targetHeight)
  File "/usr/lib/python2.7/site-packages/Gooey-1.0.0-py2.7.egg/gooey/gui/components/header.py", line 92, in _load_image
    return imageutil.wrapBitmap(sizedImage, self)
  File "/usr/lib/python2.7/site-packages/Gooey-1.0.0-py2.7.egg/gooey/gui/imageutil.py", line 23, in wrapBitmap
    bitmapData = wx.Bitmap.FromBufferRGBA(im.size[0], im.size[1], im.convert('RGBA').tobytes())
AttributeError: type object 'Bitmap' has no attribute FromBufferRGBA
```

Thank you for helping me.  ^_^

**Comment by LagrangeW** [comment] 2018-05-11 12:18
Hey, I have some issues like you, Do you solve it?

**Comment by rinka-meltiron** [comment] 2018-06-20 10:47
Anything on this, I have the same issue.

**Comment by rinka-meltiron** [comment] 2018-06-20 11:16
OK.  The problem is fixed with the following code modification:
in file gooey/gui/imageutil.py line 28.

Please change the line:
bitmapData = wx.Bitmap.FromBufferRGBA(im.size[0], im.size[1], rgba)
to
bitmapData = wx.BitmapFromBufferRGBA(im.size[0], im.size[1], rgba)

**Comment by amnonkhen** [comment] 2018-07-10 15:55
The suggestion of @rinka-meltiron works. Is this a Windows-only problem?

**Comment by rinka-meltiron** [comment] 2018-07-11 03:54
No, My machine is an Ubuntu 16.04.  I have been unable to test on Windows as I don't have an installation.

**Comment by chriskiehl** [comment] 2018-09-16 20:07
@rinka-meltiron thanks for root causing this! 

I've applied your patch. https://github.com/chriskiehl/Gooey/commit/9ab9b910d71d569dae58d86a6e5d739518133744 it'll be in the next release. 

Thanks!

**Closed by chriskiehl** 2018-09-16 20:07 UTC
