### ISSUE TITLE
text input on status screen for inputs from raw_input()

### ISSUE THREAD

**Issue by jason-neal** [chriskiehl/Gooey#124] opened 2015-11-06 15:45 UTC
I have a script that take user input via the raw_input() function in the middle of the execution.E.g.
response = raw_input('Do you want to try again Y/n?')

Currently with Gooey enabled the text in the raw_input doesn't appear in the status window until after I have entered the user input in the terminal where I began running the script.

I have gotten around the text not appearing in the status box by printing it outside of raw_input().
def raw_inputer(question):
    print(question)
    response = raw_input("")
    return response

but it is still clunky to go back on the terminal to enter the values.

Is there a way to get an input field to appear on the gui under the status window or something for when user input is needed during execution? Or with yes/no type responses some buttons that could be easy to press. 

Thanks

**Comment by drandreaskrueger** [comment] 2016-02-02 06:18
+1

**Comment by chriskiehl** [comment] 2018-01-28 02:08
Duplicate of #222

**Closed by chriskiehl** 2018-01-28 02:08 UTC
